class _Constants:
    DEFAULT_NOISE_MAP_FILENAME = "noise-map/hot_pixels.png"
    DEFAULT_MN_KERNEL_SIZE = 3
    INTERPOLATE_MEAN = 'MEAN'
    INTERPOLATE_MEDIAN = 'MEDIAN'
    RGB_LABELS = ['r', 'g', 'b']
    DEFAULT_CHANNEL_THRESHOLDS = [13, 13, 13]
    DEFAULT_BLUR_SIZE = 5
    DEFAULT_NOISE_PLOT_RANGE = [5, 30]
    VALID_INTERPOLATE = {INTERPOLATE_MEAN, INTERPOLATE_MEDIAN}

    ALIGN_HOMOGRAPHY = "ALIGN_HOMOGRAPHY"
    ALIGN_RIGID = "ALIGN_RIGID"
    BORDER_CONSTANT = "BORDER_CONSTANT"
    BORDER_REPLICATE = "BORDER_REPLICATE"
    BORDER_REPLICATE_BLUR = "BORDER_REPLICATE_BLUR"
    DETECTOR_SIFT = "SIFT"
    DETECTOR_ORB = "ORB"
    DETECTOR_SURF = "SURF"
    DETECTOR_AKAZE = "AKAZE"
    DESCRIPTOR_SIFT = "SIFT"
    DESCRIPTOR_ORB = "ORB"
    DESCRIPTOR_AKAZE = "AKAZE"
    MATCHING_KNN = "KNN"
    MATCHING_NORM_HAMMING = "NORM_HAMMING"
    DEFAULT_BORDER_BLUR = 50
    VALID_DETECTORS = [DETECTOR_SIFT, DETECTOR_ORB, DETECTOR_SURF, DETECTOR_AKAZE]
    VALID_DESCRIPTORS = [DESCRIPTOR_SIFT, DESCRIPTOR_ORB, DESCRIPTOR_AKAZE]
    VALID_MATCHING_METHODS = [MATCHING_KNN, MATCHING_NORM_HAMMING]
    VALID_TRANSFORMS = [ALIGN_RIGID, ALIGN_HOMOGRAPHY]
    VALID_BORDER_MODES = [BORDER_CONSTANT, BORDER_REPLICATE, BORDER_REPLICATE_BLUR]

    def __setattr__(self, name, value):
        raise AttributeError(f"Can't reassign constant '{name}'")


constants = _Constants()
