class _Constants:
    DEFAULT_PLOTS_PATH = 'plots'

    DEFAULT_NOISE_MAP_FILENAME = "noise-map/hot_pixels.png"
    DEFAULT_MN_KERNEL_SIZE = 3
    INTERPOLATE_MEAN = 'MEAN'
    INTERPOLATE_MEDIAN = 'MEDIAN'
    RGB_LABELS = ['r', 'g', 'b']
    RGBA_LABELS = ['r', 'g', 'b', 'a']
    DEFAULT_CHANNEL_THRESHOLDS = [13, 13, 13]
    DEFAULT_BLUR_SIZE = 5
    DEFAULT_NOISE_PLOT_RANGE = [5, 30]
    VALID_INTERPOLATE = {INTERPOLATE_MEAN, INTERPOLATE_MEDIAN}

    ALIGN_HOMOGRAPHY = "ALIGN_HOMOGRAPHY"
    ALIGN_RIGID = "ALIGN_RIGID"
    BORDER_CONSTANT = "BORDER_CONSTANT"
    BORDER_REPLICATE = "BORDER_REPLICATE"
    BORDER_REPLICATE_BLUR = "BORDER_REPLICATE_BLUR"
    DETECTOR_SIFT = "SIFT"
    DETECTOR_ORB = "ORB"
    DETECTOR_SURF = "SURF"
    DETECTOR_AKAZE = "AKAZE"
    DESCRIPTOR_SIFT = "SIFT"
    DESCRIPTOR_ORB = "ORB"
    DESCRIPTOR_AKAZE = "AKAZE"
    MATCHING_KNN = "KNN"
    MATCHING_NORM_HAMMING = "NORM_HAMMING"
    DEFAULT_BORDER_BLUR = 50
    VALID_DETECTORS = [DETECTOR_SIFT, DETECTOR_ORB, DETECTOR_SURF, DETECTOR_AKAZE]
    VALID_DESCRIPTORS = [DESCRIPTOR_SIFT, DESCRIPTOR_ORB, DESCRIPTOR_AKAZE]
    VALID_MATCHING_METHODS = [MATCHING_KNN, MATCHING_NORM_HAMMING]
    VALID_TRANSFORMS = [ALIGN_RIGID, ALIGN_HOMOGRAPHY]
    VALID_BORDER_MODES = [BORDER_CONSTANT, BORDER_REPLICATE, BORDER_REPLICATE_BLUR]

    BALANCE_LINEAR = "LINEAR"
    BALANCE_GAMMA = "GAMMA"
    BALANCE_MATCH_HIST = "MATCH_HIST"
    VALID_BALANCE = [BALANCE_LINEAR, BALANCE_GAMMA, BALANCE_MATCH_HIST]

    BALANCE_LUMI = "LUMI"
    BALANCE_RGB = "RGB"
    BALANCE_HSV = "HSV"
    BALANCE_HLS = "HLS"
    VALID_BALANCE_CHANNELS = [BALANCE_LUMI, BALANCE_RGB, BALANCE_HSV, BALANCE_HLS]

    DEFAULT_IMG_SCALE = 8
    DEFAULT_CORR_MAP = BALANCE_LINEAR
    DEFAULT_CHANNEL = BALANCE_LUMI
    DEFAULT_RANS_THRESHOLD = .50
    DEFAULT_BORDER_VALUE = [0] * 4
    DEFAULT_INTENSITY_INTERVAL = {'min': 0, 'max': -1}

    DEFAULT_R_STEPS = 100
    DEFALUT_BLACK_THRESHOLD = 1
    DEFAULT_MAX_CORRECTION = 1

    DM_ENERGY_LAPLACIAN = "laplacian"
    DM_ENERGY_SOBEL = "sobel"
    DM_MAP_AVERAGE = "average"
    DM_MAP_MAX = "max"
    VALID_DM_MAP = [DM_MAP_AVERAGE, DM_MAP_MAX]
    VALID_DM_ENERGY = [DM_ENERGY_LAPLACIAN, DM_ENERGY_SOBEL]
    DEFAULT_DM_MAP = DM_MAP_AVERAGE
    DEFAULT_DM_ENERGY = DM_ENERGY_LAPLACIAN
    DEFAULT_DM_KERNEL_SIZE = 5
    DEFAULT_DM_BLUR_SIZE = 5
    DEFAULT_DM_SMOOTH_SIZE = 32

    DEFAULT_PY_MIN_SIZE = 32
    DEFAULT_PY_KERNEL_SIZE = 5
    DEFAULT_PY_GEN_KERNEL = 0.4

    STATUS_RUNNING = 1
    STATUS_PAUSED = 2
    STATUS_STOPPED = 3

    RUN_COMPLETED = 0
    RUN_FAILED = 1
    RUN_STOPPED = 2

    def __setattr__(self, name, value):
        raise AttributeError(f"Can't reassign constant '{name}'")


constants = _Constants()
