---

name: CI multiplatform

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      #      - name: Install system dependencies
      #        run: |
      #          sudo apt-get update
      #          sudo apt-get install -y \
      #            xvfb \
      #            libxkbcommon-x11-0 \
      #            libxcb-icccm4 \
      #            libxcb-image0 \
      #            libxcb-keysyms1 \
      #            libxcb-render-util0 \
      #            libxcb-xinerama0 \
      #            libxcb-xinput0 \
      #            libxcb-xfixes0
      #
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
#          pip install pytest-xvfb

      - name: Run non-GUI tests (test_00*.py)
        working-directory: tests
        run: |
          pytest "test_00*.py" -v --disable-warnings -p no:pytest_xvfb
