name: CI Linux

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.12"

    - name: Install system dependencies for Qt (PySide6)
      run: |
        sudo apt-get update
        sudo apt-get install -y libegl1 libgl1-mesa-dev libxkbcommon-x11-0

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .[dev]

    - name: Run tests with virtual display (xvfb)
      run: |
        xvfb-run -a pytest -s
