---

name: CI Linux

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            xvfb \
            libxkbcommon-x11-0 \
            libxcb-icccm4 \
	    libxcb-image0 \
      	    libxcb-keysyms1 \
      	    libxcb-render-util0 \
      	    libxcb-xinerama0 \
      	    libxcb-xinput0 \
      	    libxcb-xfixes0

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
          pip install pytest-xvfb

      - name: Run GUI tests
        run: |
          cd tests/
          xvfb-run -a python -m pytest test_10*.py -v --disable-warnings \
            --capture=no \
            --color=no
        env:
          QT_QPA_PLATFORM: "offscreen"
          QT_DEBUG_PLUGINS: "1"
          MPLBACKEND: "Agg"
          DISPLAY: ":99"
    
        run: |
          cd tests/
          MPLBACKEND=Agg pytest test_00*.py -v --disable-warnings
        env:
          QT_QPA_PLATFORM: "offscreen"
          MPLBACKEND: "Agg"  # Doppia assicurazione

      - name: Run GUI tests
        run: |
          cd tests/
          xvfb-run -a pytest test_10*.py -v --disable-warnings
        env:
          QT_QPA_PLATFORM: "offscreen"
          MPLBACKEND: "Agg"
