---

name: Create new release

on:
  push:
    tags:
      - v**

jobs:
  publish-release:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.12"]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstall	er
          pip install -e .[dev]

      - name: Build and package release
        working-directory: scripts
        run: |
          python build_release.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: focusstack-${{ matrix.os }}
          path: dist/focusstack-release.zip

  create-release:
    needs: publish-release
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v3
        with:
          path: artifacts

      - name: Create release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          files: |
            artifacts/focusstack-ubuntu-latest/focusstack-release.zip
            artifacts/focusstack-windows-latest/focusstack-release.zip
            artifacts/focusstack-macos-latest/focusstack-release.zip
